[package]
name = "tytm"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.9", features = ["derive"] }
dirs = "5.0.1"
reqwest = { version = "0.12.5", features = ["blocking"] }
serde = { version = "1.0.204", features = ["derive", "rc"] }
serde_json = "1.0.120"
tempfile = "3.10.1"
typetag = "0.2.16"
zip = "2.1.3"
