[package]
name = "tytm"
version = "0.3.1"
edition = "2021"

[dependencies]
# File system
dirs = "5.0"
tempfile = "3.12"
zip = "2.1"

# Web access
git2 = "0.20"
reqwest = { version = "0.12", features = ["blocking"] }

# Else
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
